frase = ('  Que dia lindo para aprender programação  ')
print(len(frase))
print(frase.count('a'))
print(frase.count('a',0,15))
print(frase.find('der'))
print(frase.find('noite'))
print('curso' in frase)
print('lindo' in frase)
print(frase.replace('dia','noite'))
print(frase.upper())
print(frase.lower())
print(frase.capitalize())
print(frase.title())
print(frase.strip())
print(frase.rstrip())
print(frase.lstrip())

